CONTRIBUTING.md

Signed-off-by: Viraj Kanwade <github@virajk.otherinbox.com>

instructions for .scpt diff

---

README.md

Including VT-X instructions for Windows users.

Including VT-X instructions

---

windows/start.sh

@gmanfunky, as per your advice! I shortened the message a bit - what do you think?

Add note to help users fix tty errors with winpty

---

osx/installerplugins/overviewplugin/Base.lproj/overviewplugin.xib
windows/Toolbox.iss

Update installer message to specify anonymous information is being
collected.

Update installer message to specify anonymous information is being collected.

---

osx/installerplugins/overviewplugin/Base.lproj/overviewplugin.xib
windows/Toolbox.iss

This stood out like a sore thumb when I went through the installation today so figured I'd fix said typo.

Fix typo in anonymous

---

README.md

Signed-off-by: Ben Firshman <ben@firshman.co.uk>

Update readme to reflect Compose for Windows

---

osx/uninstall.sh

These were left behind on my box. PR simply adds the glob line to remove them.

Remove the machine drivers in uninstall

---

windows/Toolbox.iss

PR for issue #310. Make Git installation optional and allow to keep it up to date separately.
Signed-off-by: Pavel Sorokin <pavel.sorokin@nerro.eu>

Make Git installation optional

---

Makefile
docs/Dockerfile
docs/Makefile
docs/index.md

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
@jeffdm @moxiegirl

Start by creating a Docker Toolbox menu item

---

docs/Dockerfile

- remove tutorials, that repo is now private
- add notary as that component is now building
- add toolbox as that component is now building
- change ownership of kitematic to docker as that repo moved
Signed-off-by: Mary Anthony <mary@docker.com>

Removing tutorials

---

docs/Makefile
docs/index.md

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

Fix link to overview topic

---

windows/start.sh

Split Docker Machine and VirtualBox validation message into to messages to resolve #357

Split Docker Machine and VirtualBox validation message #357

---

windows/start.sh

Signed-off-by: Roland Németh <6uliver@gmail.com>

Pass start.sh first argument as a command for bash

---

docs/toolbox_install_mac.md

fix broken links per issue #30 on docs-base-1.12-integration

---

docs/toolbox_install_mac.md

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
@londoncalling @jeffdm @nathanleclaire @icecrime

Fix mac terminal image link

---

docs/toolbox_install_windows.md

fixed link

---

Dockerfile.osx
Dockerfile.windows

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

Change test.docker.com to get.docker.com for final release

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh
windows/start.sh

Fixes https://github.com/docker/toolbox/issues/539. Workaround for https://github.com/docker/docker/issues/25740 & https://github.com/golang/go/issues/16715.

clear all_proxy if not socks address

---

docs/toolbox_install_mac.md
docs/toolbox_install_windows.md

added uninstall instructions to Toolbox docs

---

docs/toolbox_install_mac.md
docs/toolbox_install_windows.md

clarified some details about Toolbox uninstall and Docker Machine

---

script/deploy.sh

Fixes #608 
Signed-off-by: Tao Wang <twang2218@gmail.com>

Add checksum file for toolbox releases

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh
windows/start.sh

This pull request fixes a grammatical issue in a comment and expands that sentence for better comprehension.
Runtime behaviour is unchanged, as only a comment is changed.

Fix comment grammar; expand for comprehension
