docker/toolbox

osx/README.md

The installation package produced by `make` is `DockerToolbox.pkg`. Updated OS X readme.

Correct name of package produced by make in OS X documentation

---

windows/Toolbox.iss

The typo was in the first setup screen:
"Send one-time, anonymous **diagonstics** during install."
Fixed the word to *diagnostics*.

Fixed tiny typo in Windows setup.

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh

`dscl /Search -read /Users/$USER UserShell | awk '{print $2}'` can output multiple user shells. For me, I have both `/bin/zsh` and `/bin/bash` on two separated line. Then the `USER_SHELL` should become `/bin/zsh /bin/bash`.
```bash
$echo $(dscl /Search -read /Users/$USER UserShell | awk '{print $2}')            
> /bin/zsh /bin/bash
```
which can lead to fatal error when you are calling `$USER_SHELL`. Because you will be calling `/bin/zsh` with first parameter as `/bin/bash`.
See #210 for details.

Only select one shell

---

windows/start.sh

Fixes #183 and #220. Creates an alias for docker that uses winpty when using the Docker Quickstart Terminal.
Credit for fix: @gmanfunky. Thank you!
cc @nathanleclaire @mchiang0610. What are your thoughts?
Interestingly enough, this also works for `docker-compose` @aanand @dnephin

Fix tty errors using winpty

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh
windows/start.sh

I had the same problem commented in issue #157, that issue is marked as closed, but I think that it's still an issue, because, although it can be manually fixed afterwards, it can be quite disappointing to have to manually create a new docker-machine and set a bigger disk size to keep using Docker, having to re-build everything from scratch.
I think the default shouldn't be only 20 GB of disk, knowing that VirtualBox creates a dynamic disk size, it only takes as much (real) space as it is needing (starts with just 200 MB), limited by a maximum of the specified disk size.
In my case, after having several images built and working I got my VM disk space full, and having to re-build every image (in a new, modified docker-machine) with a not-so-speedy connection is sort of painful.
Also, I …

Start default machine with dynamic disk size of max 1 TB instead of 20 GB

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh
windows/start.sh

Docker-machine now seems to throw an error when starting a running VM, which causes start.sh to fail with a rather unhelpful message.  Checking to see what the status of the VM is before we start it prevents this error.

Verify boot2docker VM is not running before starting it

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh
windows/start.sh

@FrenchBen PTAL
- Cleaned up improper use of brackets when referencing some variables in the bash scripts.
- Tested on Mac and Windows with cases: 
- VM non existant
- VM error
- VM stopped
- VM running

Properly verify that VM does not exist before removing machine files

---

windows/Toolbox.iss

Editing this file was a pain due to mixture of tabs and spaces for indentation.  This replaces all tabs with 2 spaces (which is the indentation used throughout the file wherever tabs weren't used).
As a Pythonista I found spaces preferable.  However, if preferred, I can amend this to use tabs instead for consistency with Go style :)
Signed-off-by: Erik M. Bray <erik.bray@lri.fr>

Whitespace cleanup: Replace all tabs with two spaces

---

windows/Toolbox.iss

The 'Welcome' page, which among other things displays the error reporting / tracking checkbox, was not being displayed when running the installer.
I'm actually a little confused about this, because I could have sworn I remember seeing this when running the Docker Toolbox installer in the past.  However, now I am certain it is not displaying the welcome page.
There was a possibility this page was being skipped due to there already being a record of my having installed Docker Toolbox in the windows registry.  However, looking through the Inno Setup source code it's clear that the *only* way the welcome page would be skipped is if `DisableWelcomePage=yes`, which for some reason happens to be the default.
Signed-off-by: Erik M. Bray <erik.bray@lri.fr>

Re-enable welcome page

---

windows/start.sh

This is a fix to https://github.com/docker/toolbox/issues/368.
Thanks to @Bakudankun who found how to correct the problem.

Fix issue `docker run image bash -c "multiple parameters"`

---

windows/Toolbox.iss

Just fixes some minor and harmless warnings I noticed in the Inno Setup output.  For reference, the warnings were:
```
Warning: The [Setup] section directive "WizardImageBackColor" is obsolete and ignored in this version of Inno Setup.
Warning: Line 144, Column 2: [Hint] Variable 'TRACKING' never used
Warning: Line 97, Column 2: [Hint] Variable 'RESTART' never used
```

Removed unused variables and deprecated setup directive

---

windows/Toolbox.iss

NDIS6 host network filter driver is known to cause issues on some Windows
versions. VirtualBox installs The NDIS6 driver by default for Windows Vista and later.
For older Windows versions, the installer will automatically select the NDIS5
driver and this cannot be changed. This commit provides an option for Windows Vista
and later users to install the (legacy) NDIS5 host network filter driver.
Signed-off-by: Todor Minchev <todor.minchev@linux.intel.com>

add VirtualBox NDIS5 driver option to the installer

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh
windows/start.sh

This attempt to solve the proxy issue when installing docker-toolbox on windows, but i believe the same mechanism could be used on mac as well. See #78. There is still work to be done for Kitematic.
This solution use the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` system variables and pass them to the `docker-machine` `--engine-env` parameters.
Don't forget to set the NO_PROXY system variable with at least the 192.168.99.100/101/102/103... IPs and dns names used to access local servers like 'kitematic', 'default', 'dev'.
This successfully launch the Docker Quickstart Terminal on windows if you set your *_PROXY variables as environnement variables before the first launch (in Control Panel). I believe this is the standard way to set proxy infos on Windows, Mac and Linux.

Add proxy variables to docker-machine command if they exists

---

windows/start.sh

using the env variable VMNAME
Replacement for https://github.com/docker/toolbox/pull/426
@nathanleclaire 
Signed-off-by: Markos Rendell <markosrendell@gmail.com>

Allowing you to override 'default' as the name for a machine 

---

osx/uninstall.sh

After removing the binaries it is recommended to forget the install state of the packages.

Forget install state of docker packages

---

docs/Dockerfile
docs/Makefile
docs/toolbox_install_mac.md
docs/toolbox_install_windows.md

Docs checker can now resolve the docker for * links on docs.docker.com - and thus should pass.

Now that the Docker4 links are online, we can use them

---

README.md

Added info and links to check if VT-X is enabled and how to enable it.
Added info about potential other issues of Toolbox not running when installed before enabling VT-X
Documentation pertains to issues docker/toolbox#166 and docker/docker#16182
Signed-off-by: Kevin Blum <kblum96@gmail.com>

Added documentation pertaining to VT-X virtualization being enabled when installing Toolbox

---

windows/start.sh

Just for reference @dgageot @rneugeba -- I noticed that the PATH for binaries set by Docker for Windows clobbers the path for Toolbox binaries (this may or may not be the behavior for all installs, but it was for my existing Toolbox-D4W VM).  So, my versions of everything were off when I installed the Toolbox RC.  This patch should fix the behavior for users of the "Quickstart" terminal but it's possible some users will hit this issue through other means, so be advised.
Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

Force Toolbox bin path to start of PATH

---

docs/overview.md

Added pointers to Docker for Mac and Docker for Windows to make sure people know those new products are out there, and to help clarify the difference between d4mac, d4win and Toolbox.

added info about d4mac and d4win for v1.12 publish set

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh
windows/start.sh

* Fix `if` statements - based on my tests and https://stackoverflow.com/questions/3869072/test-for-non-zero-length-string-in-bash-n-var-or-var the current method will always return true even if `PROXY` environment variables are not set
* Improves on https://github.com/docker/toolbox/pull/183
* Replace inconsistent tabs in `start.sh` with spaces like exists elsewhere in `start.sh`

improve proxy variables check

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh
windows/start.sh

Set `--no-proxy` flag as documented at https://docs.docker.com/machine/reference/env/#/excluding-the-created-machine-from-proxies. Fixes issues many people have when using a proxy.
Originally suggested by @nathanleclaire at https://github.com/docker/toolbox/pull/183#issuecomment-197066248

set no proxy flag - exclude machine from proxy

---

Jenkinsfile

The documentation has been migrated to docker/docker.github.io, so I'm removing this Jenkins file that was running docs-related CI and can start breaking the builds.
Signed-off-by: Joao Fernandes joao.fernandes@docker.com

Remove Jenkinsfile used for docs CI

---

windows/Toolbox.iss

Change replaces 'userdocs' variable usage with 'userappdata' to account for users with 'My Documents' locations which are not the default windows location. Tested on windows 7 pc with network drive location as 'My Documents'. This addresses issue https://github.com/docker/toolbox/issues/435

Fix for windows installer where 'My Documents' is not in the default location

---

script/release.sh

Some feedback on the release tool:
- Needs to be ran from root directory
- got the following error the first time I ran it: `./script/release.sh: line 21: github-release: command not found`
The above didn't have any info, thus I assumed you had installed this: go get github.com/aktau/github-release

GitHub release

---

script/build-osx
script/build-windows

`docker cp` does not require the container to be running, so just _create_ the container instead of running it.

Don't start container before copy

---

osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh
windows/start.sh

with change e95cada26c20e96da18b183cb92597127669fa8c,
the debug funkton was broken if used with
`export MACHINE_DEBUG="1"`

fix broken DOCKER_MACHINE debug, see also e95cada26c20e96da18b183cb92597127669fa8c

---

osx/uninstall.sh

An `rm -rf` of `/Applications/Docker` passes silently, but doesn't remove `/Applications/Docker.app`

Correct path to remove /Applications/Docker.app

---

windows/Toolbox.iss
windows/docker-terminal.cmd
windows/start.sh

**Applies to Windows only**
This PR is the culmination of a few changes I made in to my docker toolbox build and setup, in order to be able to easily use `docker`, `docker-compose`  from any terminal in windows i.e. cmd, powershell, git-bash etc
It is quite tedious to only have access to the `docker` command through the "Docker Quickstart Terminal" (DQT) on the start menu. Moreover DQT is setup to start from the same directory each time; in real day-to-day work, this is almost never the directory you want to be in.
I have made changes to the start.sh script to make it portable. I have also introduced the file docker-terminal.cmd which simply runs the start.sh.. The advantage of docker-terminal is that one can simply open up their project in a specific directory (e.g. with "Open command …

[Windows] A More robuse "Docker Quickstart Terminal"
